### ISSUE TITLE
貌似学校vpn系统更新了 插件点开500报错

### ISSUE THREAD

**Issue by pea4** [qwertycxz/NUIST-VPN#2]
阿巴阿巴阿巴

**Comment by qwertycxz** [comment]
呃……我看了看,现在学校vpn的重定向已经加密了,解密并不现实……
我正在考虑用重定向解决问题,看看能不能白嫖一下别人的服务器重定向

**Comment by qwertycxz** [comment]
好吧,我白嫖了一下夹总的服务器,现在扩展能用了
